;/* Version 1ad6f7ca4d96e75e9ff37bb1b3973ecc v:4.3.2.0, c:5a2e4fdec8aec1835706a31a9312f8a1616609c7, b:9268 n:13-4.3.2.next-build */(function(){/*


 Copyright (c) 2013, AppDynamics, Inc. All rights reserved.

 Derivative of Google Episodes:

 Copyright 2010 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

 See the source code here:
 http://code.google.com/p/episodes/
*/
new function(){var g=window.ADRUM;if(g&&g.q&&!0!==window["adrum-disable"]){(function(a){(function(b){b.O=function(f){function e(a){return a.replace(/\s/g,"")===d}var c={a:[1,2,3,"str"]},d='{"a":[1,2,3,"str"]}';if("undefined"!==typeof JSON&&JSON&&b.isFunction(JSON.stringify)&&e(JSON.stringify(c)))return JSON.stringify(f);if("undefined"!==typeof Object&&Object&&b.isFunction(Object.toJSON)&&e(Object.toJSON(c)))return Object.toJSON(f);a.error("M69");return null};b.Ma=function(f,e,c){var d=f,h=c;"xhr"===
c&&(d=document.createElement("div"),f.appendChild(d),h="xhr_"+f.getElementsByTagName("div").length);f=document.createElement("p");f.innerHTML="Script loaded from "+a.conf.adrumExtUrl+". Metrics collected are:";d.appendChild(f);f=document.createElement("table");f.id="ADRUM_"+h;var h=document.createElement("tbody"),q;for(q in e){c=document.createElement("tr");var b=document.createElement("td");b.innerHTML=q;b.className="name";var k=document.createElement("td");k.innerHTML=String(e[q]);k.className="value";
c.appendChild(b);c.appendChild(k);h.appendChild(c)}f.appendChild(h);d.appendChild(f)};b.Df=function(){function a(e,c){try{if("object"!=typeof e)return String(e);if(0<=b.Ga(c,e))return"Already visited";c.push(e);var d;if(b.isArray(e)){for(var h="[ ",q=0;q<e.length;q++)0!=q&&(h+=", "),h+=a(e[q],c);d=h+" ]"}else{var h="{ ",q=!0,m;for(m in e)q?q=!1:h+=", ",h+=a(m,c)+" => "+a(e[m],c);d=h+" }"}return d}catch(k){return"dumpObject failed: "+k}}return function(e){return a(e,[])}}();b.Ga=b.isFunction(Array.prototype.indexOf)?
function(a,e){return a.indexOf(e)}:function(a,e){for(var c=0;c<a.length;c++)if(a[c]==e)return c;return-1};b.Eg=function(a){return b.isObject(a)&&b.isDefined(a.document)&&b.isDefined(a.self)&&a.self===a};b.compareWindows=function(a,e){return a==e};b.Sa=function(a,e,c,d,h){if(!b.isDefined(e))return e;if(b.isArray(e)){a=[];for(var q=0,m=e.length;q<m;q++)a[q]=b.Sa(q,e[q],c,d,h);return a}if(b.isFunction(e))return e;if(b.isObject(e)){a={};for(q in e)b.hasOwnPropertyDefined(e,q)&&(a[c(q)]=h&&h(q)?e[q]:b.Sa(q,
e[q],c,d,h));return a}return d(a,e)};b.Jg=function(a){var e=[],c;for(c in a)b.hasOwnPropertyDefined(a,c)&&e.push([c,a[c]]);return e};b.yh=function(){try{localStorage.setItem("try","try");var a=localStorage.getItem("try");localStorage.removeItem("try");return"try"===a}catch(e){return!1}};b.xh=function(){try{var a=b.O({v:1});return 1===JSON.parse(a).v}catch(e){return!1}};b.zh=function(){return b.isFunction(window.postMessage)};b.tf=function(a,e){var c=document.createElement("div");c.innerHTML='<iframe id="'+
e+'" src='+a+' width="0" height="0" tabindex="-1" title="empty" style="display: none;"></iframe>';document.body.appendChild(c);return document.getElementById(e)};b.oh=function(a,e){b.isDefined(e)&&(a.parentPageName=e)};b.Ua=function(a){return b.isNumber(a)&&isFinite(a)&&Math.floor(a)===a};b.kc=function(b){a.log(b);console&&console.log&&console.log(b)}})(a.utils||(a.utils={}))})(g||(g={}));(function(a){(function(a){a.Cd=function(a){return/^[0-9]+$/.test(a)?Number(a):null};a.Kc=function(a){return"number"===
typeof a&&!isNaN(a)&&isFinite(a)}})(a.utils||(a.utils={}))})(g||(g={}));(function(a){(function(b){function f(d){var c=d.split("\r\n"),e=/^\s*ADRUM_(\d+): (.+)\s*$/i;d=[];for(var b=0;b<c.length;b++){var f=c[b];try{var g=e.exec(f);g&&d.push([Number(g[1]),g[2]])}catch(l){a.exception(l,"M72",f)}}Array.prototype.sort.call(d,function(a,d){return a[0]-d[0]});g=[];for(c=0;c<d.length;c++)g.push(d[c][1]);return g}var e=a.utils.hasOwnPropertyDefined,c=null,d=null;b.Cc=function(){d||(d=b.Xc(b.bb(b.cookieMetadataChunks),
b.bb(a.footerMetadataChunks)));return d};b.getPageGUID=function(){var d=a.monitor.DOMEventsMonitor,e=a.utils.isObject(d.currentBasePage)&&a.utils.isFunction(d.currentBasePage.guid);if(!c){var f=b.Cc();c=f&&f.clientRequestGUID||(e?d.currentBasePage.guid():a.utils.generateGUID())}return c};b.cg=function(d){d=f(d);a.log("M70",d);return b.Xc(b.bb(d))};b.Xc=function(d,c){function e(d){for(var h=0;h<d.length;h++){var c=d[h];c!=f&&0>a.utils.Ga(l,c)&&l.push(c)}}if(!d||0>=d.L.length)return null;c||(c=d);var f;
if(0<c.L.length){if(f=c.L[0],0>a.utils.Ga(d.L,f))return null}else return a.error("M71"),null;var g=c.serverSnapshotType||d.serverSnapshotType,n=c.hasEntryPointErrors||d.hasEntryPointErrors,l=[];e(d.L);e(c.L);var r={clientRequestGUID:f,btGlobalAccountName:d.btGlobalAccountName};0<l.length&&(r.otherClientRequestGUIDs=l);0<b.Wc(d.btTime,c.btTime).length&&(r.btTime=b.Wc(d.btTime,c.btTime));null!==g&&(r.serverSnapshotType=g);null!==n&&(r.hasEntryPointErrors=n);return r};b.Wc=function(a,d){for(var c=a.concat(d),
b={},f={},g=0;g<c.length;g++){var l=c[g];l.id in b||(b[l.id]=-1);b[l.id]=Math.max(b[l.id],l.duration);l.id in f||(f[l.id]=-1);f[l.id]=Math.max(f[l.id],l.ert)}var c=[],r;for(r in b)e(b,r)&&c.push({id:r,duration:b[r],ert:f[r]});return c};b.bb=function(d){if(!a.utils.isArray(d))return null;for(var c=[],e=null,b=[],f=null,g=null,l=0;l<d.length;l++){var r=d[l];if("string"!==typeof r)return null;r=r.replace(/^"|"$/g,"");r=decodeURIComponent(r).split(",")[0].replace(/^\s+|\s+$/g,"").split(":");if(2===r.length){var t=
r[1];switch(r[0]){case "clientRequestGUID":case "g":c.push(t);break;case "btId":case "i":b.push({id:t,duration:-1,ert:-1});break;case "btDuration":case "d":if(0===b.length)return null;r=a.utils.Cd(t);if(!a.utils.Kc(r)||-1>r)return null;b[b.length-1].duration=r;break;case "btERT":case "e":if(0===b.length)return null;r=a.utils.Cd(t);if(!a.utils.Kc(r)||-1>r)return null;b[b.length-1].ert=r;break;case "serverSnapshotType":case "s":f=t;break;case "globalAccountName":case "n":e=t;break;case "hasEntryPointErrors":case "h":g=
t}}}return 0===c.length?null:{L:c,btGlobalAccountName:e,btTime:b,serverSnapshotType:f,hasEntryPointErrors:g}};b.Ai=f})(a.correlation||(a.correlation={}))})(g||(g={}));(function(a){var b=a.conf||(a.conf={});b.Wh=3E3;b.Hd=a.isDebug;b.Xe=1E3;b.ye=2;b.xe=5;b.se=5;b.te=20;b.Jb=5E3;b.J=512;b.ce=10;b.be=64;b.Ie=10;b.He=10;b.De=300;b.Lb=2048;b.U=2048;b.Xh=760;b.Tc={eumAppKey:"ky",userPageName:"un",clientRequestGUID:"cg",otherClientRequestGUIDs:"og",baseGUID:"bg",parentGUID:"mg",parentPageUrl:"mu",parentPageType:"mt",
parentLifecyclePhase:"pp",pageType:"pt",pageUrl:"pu",pageReferrer:"pr",pageTitle:"pl",pageName:"pn",httpHeaders:"hh",parameter:"pa",navOrXhrMetrics:"mn",cookieMetrics:"mc",resourceTimingInfo:"rt",userData:"ud",userDataLong:"udl",userDataDouble:"udd",userDataBoolean:"udb",userDataDate:"udt",errors:"er",ajaxError:"ae",xhrStatus:"xs",btTime:"bt",btGlobalAccountName:"btgan",serverSnapshotType:"ss",hasEntryPointErrors:"se",dataType:"dt",geoCountry:"gc",geoRegion:"gr",geoCity:"gt",localIP:"lp",ip:"ip",
BEACONS:"B",ver:"vr",eom:"em",agentId:"ai",rootGUID:"rg",events:"es",guids:"gs",urlParts:"up",sequenceId:"si",eventType:"et",eventGUID:"eg",parentType:"at",serverMetadata:"sm",eventUrl:"eu",line:"ln",message:"dm",duration:"dn",id:"id",ert:"ert",parentUrl:"au",parentPageName:"an",geo:"ge",metrics:"mx",timestamp:"ts",country:"c",region:"r",city:"t",method:"md",clientId:"ci"}})(g||(g={}));(function(a){a=a.beacons||(a.beacons={});a.numBeaconsSent=0;a.beaconsSent=[]})(g||(g={}));(function(a){(function(b){var f=
function(){function e(){}e.prototype.send=function(c,d){var h=(d?a.conf.beaconUrlHttps:a.conf.beaconUrlHttp)+a.conf.corsEndpointPath+"/"+a.conf.appKey+"/adrum",e;a.utils.isFunction(a.xhrConstructor)&&a.utils.isFunction(a.xhrOpen)?(e=new a.xhrConstructor,a.xhrOpen.call(e,"POST",h)):(e=new XMLHttpRequest,e.open("POST",h));e.setRequestHeader("Content-type","text/plain");var f=a.utils.O(c);null!=f&&(a.utils.isFunction(a.xhrSend)?a.xhrSend.call(e,f):e.send(f),a.log("M73"+h+"\n"),a.log("<hr/>"),a.isDebug&&
b.beaconsSent.push(c),b.numBeaconsSent+=1)};return e}();b.Yd=f})(a.beacons||(a.beacons={}))})(g||(g={}));g||(g={});(function(a){var b=function(){function b(a,c,d){this.qa=a;this.mg=c;this.qb=d}b.prototype.Bc=function(){try{return b.xc(this.mg.ADRUM)}catch(e){return a.error("M74"),b.xc(a)}};b.xc=function(a){return a.correlation.getPageGUID()};return b}();a.Vd=b})(g||(g={}));(function(a){a.beacons||(a.beacons={})})(g||(g={}));(function(a){(function(a){var f=function(){function e(){this.ma=[];this.Na=
{}}e.prototype.pa=function(c){if(!c)return"";if(a.hasOwnPropertyDefined(this.Na,c))return this.Na[c];var d=this.ma.length;this.Na[c]=d;this.ma[d]=c;return d};return e}();a.Ib=f})(a.utils||(a.utils={}))})(g||(g={}));(function(a){(function(b){var f=a.utils.map,e=function(){function a(){}a.th=function(a){a=(a||"").match(/([^:\/?#]+:\/\/)?([^?#]+)?(\?[^#]*)?(#[\s\S]*)?/);var c={};a[1]&&(c.protocol=a[1].substring(0,a[1].length-3));a[2]&&(c.path=a[2]);a[3]&&(c.fh=a[3]);a[4]&&(c.anchor=a[4]);return c};a.Hf=
function(d,h){var e=a.th(d),b="";e.protocol&&(b+=h.pa(e.protocol),b+="://");e.path&&(b+=f(e.path.split("/"),h.pa,h).join("/"));return b+=f([e.fh,e.anchor],function(a){return a?a[0]+h.pa(a.slice(1)):""},h).join("")};a.Ff=function(a,c){return""+c.pa(a)};return a}();b.zb=e})(a.beacons||(a.beacons={}))})(g||(g={}));(function(a){(function(b){(function(b){function e(){var c=null,h=null;try{c=localStorage[d]}catch(e){}if(c)try{c=h=JSON.parse(c),a.utils.isObject(c)&&a.utils.isNumber(c[m])&&-1<c[m]?k=h:a.error("M75")}catch(b){a.exception(b,
"M76");try{delete localStorage[d]}catch(f){a.exception(f,"M77")}}}function c(){try{var c=a.channel,e=k[h]||k[q],b=c&&c.I&&c.I.F&&c.I.F.id||(a.utils.isString(e)?e:a.utils.generateGUID());k[h]=k[q]=b;localStorage[d]=a.utils.O(k)}catch(f){}}var d="ADRUM_CLIENTINFO",h="agentId",q="clientId",m="seqId",k;e();k||(k={seqId:0});c();b.Uf=function(){e();var a=k[m]++;c();return a}})(b.gc||(b.gc={}))})(a.ud||(a.ud={}))})(g||(g={}));(function(a){(function(b){var f=function(){function e(){this.Q={na:!1};this.hd=
/;jsessionid=[^/?]+/;b.mergeJSON(this.Q,a.conf.userConf.Q);b.isBoolean(this.Q.na)||b.isArray(this.Q.na)||(a.log("M78"),this.Q.na=!1)}e.sh=function(a){for(var d=0,h=0;h<a.length;h++)d=(d<<5)-d+a.charCodeAt(h),d|=0;return d};e.prototype.bg=function(a){var d="",h,e;if(!b.isString(a))return"";h=a.indexOf("?")+1;0<h&&(e=a.indexOf("#"),0>e?d=a.substring(h):h<=e&&(d=a.substring(h,e)));return d};e.prototype.Kf=function(a){var d="",h=this.Q.na,e={},f=0,k,g,n;if(!b.isString(a)||""===a)return"";if(!1===h)return a;
k=this.bg(a);if(""===k)return a;if(b.isArray(h)){for(n=0;n<h.length;n++)e[h[n]]=!0;h=k+"&";for(n=0;n<h.length;n++)switch(h[n]){case "=":g=h.substring(f,n);break;case "&":case ";":g=g||h.substring(f,n),n++,e[g]||(d+=h.substring(f,n)),f=n,g=null}d=d.substring(0,d.length-1)}""==d&&(k="?"+k);return a.replace(k,d)};e.prototype.H=function(a){if(null===a||void 0===a)return null;if(""===a)return"";var d=a.match(this.hd),h=a;if(null!=d){var e=a.indexOf("?");if(0>e||e>d.index)h=a.replace(this.hd,"")}return h=
this.Kf(h)};e.prototype.qc=function(a){if(null===a||void 0===a)return null;var d=a.indexOf("?"),h=a.indexOf("#");0>d&&(d=Number.MAX_VALUE);0>h&&(h=Number.MAX_VALUE);return a.substring(0,Math.min(d,h))};e.prototype.Sg=function(a){if(null===a||void 0===a)return null;var d=this.qc(a);return d+"?"+e.sh(a.substring(d.length))};return e}();b.bi=f;b.n=new f})(a.utils||(a.utils={}))})(g||(g={}));(function(a){a=a.R||(a.R={});a.N||(a.N={})})(g||(g={}));(function(a){a=a.R||(a.R={});a.N||(a.N={})})(g||(g={}));
(function(a){(function(b){(function(b){var e=function(){function c(d,h,c){this.gh=0;this.fb=[];this.Fc=!1;this.gg=c;var e=this;a.utils.addEventListener(window,"message",function(a){e.Xg(a)});this.fg=a.utils.tf(h,d)}c.prototype.Xg=function(d){var c;try{if(c=JSON.parse(d.data),a.utils.isDefined(c)&&!0===c.success)if(-1===c.id&&"iframe-ready"===c.data)this.Fc=!0,this.gg();else{if(this.fb[c.id])this.fb[c.id](c.data)}else a.error("M79"+d.data+"]")}catch(e){a.exception(e,"M80")}};c.prototype.send=function(d,
c,e,b){if(this.Fc){var f=this.gh++;this.fb[f]=b;this.fg.contentWindow.postMessage(a.utils.O({id:f,action:d,key:c,value:e}),"*")}};c.prototype.generateGUID=function(a,c){this.send("generateGUID",a,null,c)};return c}();b.$d=e})(b.N||(b.N={}))})(a.R||(a.R={}))})(g||(g={}));(function(a){(function(b){var f=function(){function d(){this.$b=new e(d.Rd);this.Od=new e(d.Td);this.Rh=new c(d.Sd)}d.prototype.init=function(c){this.channel=c;a.utils.yh()&&a.utils.xh()?a.utils.zh()&&d.Fg()?this.Ih():this.Id():d.Yc=
!0};d.prototype.Id=function(){var c=this.$b.load();d.Cg(c)||(c={ver:a.conf.agentVer,id:a.utils.generateGUID()},this.$b.save(c));d.F=c};d.prototype.Ih=function(){var c=this.Od.load();if(d.Dg(c))d.F=c;else{a.log("M81");var e=this;this.Rh.load(function(c){c&&(c={ver:a.conf.agentVer,id:c,ttl:(new Date).getTime()+d.de},e.Od.save(c),d.F=c,a.log("M82"))});e=this;a.utils.tryPeriodically(d.Ha,function(){return e.isReady()},function(){e.onReady()},function(){e.$a()})}};d.Fg=function(){return a.conf.userConf&&
a.conf.userConf.xd&&a.conf.userConf.xd.enable};d.Cg=function(a){return a&&a.id&&0<a.id.length};d.Dg=function(a){return a&&a.id&&0<a.id.length&&0===a.id.indexOf("XD_")&&a.ttl>(new Date).getTime()};d.prototype.isReady=function(){return d.Yc||a.utils.isDefined(d.F)};d.prototype.onReady=function(){this.channel.onResolverReady()};d.prototype.$a=function(){a.log("M83");this.Id();this.channel.onResolverReady()};d.Ha=function(a){return 10<a?-1:[1,50,100,500][a-1]||1E3};d.Rd="ADRUM_AGENT_INFO";d.Td="ADRUM_XD_AGENT_INFO";
d.Sd="ADRUM_XD_AGENT_ID";d.de=6048E5;d.Yc=!1;return d}();b.I=f;var e=function(){function d(a){this.Zb=a}d.prototype.load=function(){var d=null;try{var c=localStorage.getItem(this.Zb);c&&(d=JSON.parse(c))}catch(e){a.exception(e,"M84")}return d};d.prototype.save=function(d){try{var c=a.utils.O(d);c&&localStorage.setItem(this.Zb,c)}catch(e){a.exception(e,"M85")}};return d}(),c=function(){function d(a){this.ef=a}d.prototype.load=function(d){var c=this;try{var e=new a.R.N.$d("cross-domain-store-server-iframe",
a.conf.adrumXdUrl,function(){e.generateGUID(c.ef,d)})}catch(b){a.exception(b,"M86")}};return d}()})(a.channel||(a.channel={}))})(g||(g={}));(function(a){(function(b){var f=a.utils.isString,e=function(){function c(){}c.prototype.Xa=function(d,e,b){d={ver:a.conf.agentVer,dataType:"R",rootGUID:b.Bc(),events:d};a.channel.I.F&&a.channel.I.F.id&&(d.agentId=a.channel.I.F.id);e&&(d.geo=e);return c.ah(d)};c.ah=function(d){a.isDebug||(d=c.pf(d));return d};c.pf=function(d){var e=new a.utils.Ib,q=new a.utils.Ib;
d=a.utils.Sa(null,d,c.Ra,function(d,k){f(k)&&k.length>a.conf.Lb&&(k=k.substr(0,a.conf.Lb));c.Bg(d)&&(f(k)&&k.length>a.conf.J&&(k=3<a.conf.J?k.substr(0,a.conf.J-3):"",k+="..."),k=b.zb.Hf(k,e));c.ug(d)&&(k=b.zb.Ff(k,q));return k},c.Lg);d[c.Ra("guids")]=q.ma;d[c.Ra("urlParts")]=e.ma;return d};c.Bg=function(a){return"eventUrl"==a||"parentUrl"==a||"pageReferrer"==a||"pageUrl"==a||"u"==a};c.ug=function(a){return"eventGUID"==a||"parentGUID"==a||"rootGUID"==a||"clientRequestGUID"==a};c.Ra=function(d){if(a.conf.Hd)return d;
var c=a.conf.Tc[d];return"undefined"===typeof c?d:c};c.Lg=function(a){a=""+a;return 0===a.indexOf("userData")||"parameter"===a};return c}();b.Xd=e})(a.beacons||(a.beacons={}))})(g||(g={}));(function(a){(function(b){var f=function(){function e(){}e.prototype.send=function(a,d){for(var e=0;e<a.length;e++)this.mh(a[e],d)};e.prototype.mh=function(c,d){var e=(d?a.conf.beaconUrlHttps:a.conf.beaconUrlHttp)+a.conf.imageEndpointPath,f=document.createElement("img");try{f.src=e+c}catch(g){}a.isDebug&&b.beaconsSent.push(c);
b.numBeaconsSent+=1};return e}();b.oe=f})(a.beacons||(a.beacons={}))})(g||(g={}));(function(a){(function(a){a.ba=function(a,e){if(3>=e)return"...";a.length>e&&(a=a.substring(0,e-3)+"...");return a};a.Ed=function(a,e){if(3>=e)return"...";a.length>e&&(a=a.substring(0,(e-3)/2)+"..."+a.substring(a.length-(e-3)/2,a.length));return a};a.Fh=function(f,e){f.length<=e||(f=a.ba(f,e-1),f+=":");return f};a.Dh=function(f,e,c,d,h,q){f=a.Fh(f,d);c=a.ba(c,h);f.length+e.length+c.length>q-3&&(e=a.ba(e,q-3-f.length-
c.length));return 0<c.length?f+"//"+e+":"+c:f+"//"+e};a.Eh=function(f,e,c){f=a.map(f,function(d){return a.Ed(d,e)});if(f.length>c){var d=f[0];f=f.slice(f.length-c);f.unshift("...");""==d&&f.unshift(d)}return f};a.Gh=function(f,e,c,d,h){d=a.Dh(f.protocol,f.hostname,f.port,d,h,e);c--;h=a.ba(f.search,e);c--;var q=a.ba(f.hash,e);c--;f=f.pathname.split("/");var g="";0<f.length&&(g=f.pop(),g=a.Ed(g,e),c--);f=a.Eh(f,e,c);return 0==f.length?d+g+h+q:d+f.join("/")+"/"+g+h+q}})(a.utils||(a.utils={}))})(g||(g=
{}));(function(a){(function(a){var f=function(){function a(){}a.Ta=function(){for(var c=0;c<a.Gb.length;c++)a.C[a.Gb[c]]=a.w.je;for(c=0;c<a.Eb.length;c++)a.C[a.Eb[c]]=a.w.ge;a.C.js=a.w.Re;a.C.css=a.w.CSS;a.C.svg=a.w.Te;a.C.html=a.w.Fb;a.C.htm=a.w.Fb};a.Qa=function(a){return a.duration?a.duration:a.responseEnd&&a.startTime?a.responseEnd-a.startTime:-1};a.Ac=function(c){var d;return(c=c.pathname)&&-1!=(d=c.lastIndexOf("."))?a.C[c.substring(d+1,c.length).toLowerCase()]||a.w.Ob:a.w.Ob};a.w={je:"img",
Re:"script",CSS:"css",Te:"svg",Fb:"html",ge:"font",Ob:"other"};a.Gb="bmp gif jpeg jpg png webp".split(" ");a.Eb=["ttf","woff","otf","eot"];a.C={};return a}();a.V=f;f.Ta()})(a.events||(a.events={}))})(g||(g={}));(function(a){(function(a){var f=function(){function a(c){function d(a){h.marks.push(0==c[a]?-1:Math.round(c[a]-h.$c))}this.marks=[];var h=this;this.$c=c.startTime;this.sg(c)?(this.uc=a.Ab,d("startTime"),d("fetchStart")):(this.uc=a.Qb,d("startTime"),d("redirectStart"),d("redirectEnd"),d("fetchStart"),
d("domainLookupStart"),d("domainLookupEnd"),d("connectStart"),d("connectEnd"),d("requestStart"),d("responseStart"));d("responseEnd")}a.Vf=function(){var c={};c[a.Qb]=a.Qe;c[a.Ab]=a.Zd;return c};a.prototype.sg=function(a){return this.B(a.redirectStart)&&this.B(a.redirectEnd)&&this.B(a.domainLookupStart)&&this.B(a.domainLookupEnd)&&this.B(a.connectStart)&&this.B(a.connectEnd)&&this.B(a.requestStart)&&this.B(a.responseStart)&&this.B(a.secureConnectionStart)};a.prototype.B=function(a){return!a||0===a};
a.Qb=1;a.Ab=2;a.Qe="startTime redirectStart redirectEnd fetchStart dnsLookupStart dnsLookupEnd connectStart connectEnd requestStart responseStart responseEnd".split(" ");a.Zd=["startTime","fetchStart","responseEnd"];return a}();a.Pb=f})(a.events||(a.events={}))})(g||(g={}));(function(a){(function(a){var f=function(){function a(){}a.prototype.ya=function(a,d){if(a)return a.slice(0,d)};return a}();a.he=f})(a.events||(a.events={}))})(g||(g={}));(function(a){(function(a){var f=function(){function e(){}
e.prototype.ya=function(c,d){if(c){if(c.length<=d)return c;for(var e=[],f=0;f<c.length;f++)e.push({gb:c[f],index:f});e.sort(function(d,c){return-(a.V.Qa(d.gb)-a.V.Qa(c.gb))});e=e.slice(0,d);e.sort(function(a,d){return a.index-d.index});for(var g=[],f=0;f<e.length;f++)g.push(e[f].gb);return g}};return e}();a.Tb=f})(a.events||(a.events={}))})(g||(g={}));(function(a){(function(a){var f=function(){function e(){}e.prototype.ya=function(c,d){if(c){if(c.length<=d)return c;for(var e=1,f=Math.floor(Number.MAX_VALUE/
4),g=c.length;e<f;){for(var k=c.length-1;0<=k;k--)if(a.V.Qa(c[k])<e&&(c.splice(k,1),g--),g<=d)return c;e*=4}return(new a.Tb).ya(c,d)}};return e}();a.Pe=f})(a.events||(a.events={}))})(g||(g={}));(function(a){(function(b){var f=a.utils.hasOwnPropertyDefined,e=function(){function d(e,f){this.version=2;this.resourceTimingInfo={};this.Ic={};this.Jc={};this.ld={};this.md={};this.hb=[];this.bf=function(d,e){if(d&&e&&0<e.length){this.Bh=d;for(var h=new c,f=new c,q=0;q<e.length;q++){var g=e[q],m=a.utils.parseURI(a.utils.n.H(g.name)),
y=g.initiatorType,z=b.V.Ac(m),x=new b.Pb(g);this.hb.push({u:this.Hh(m),i:h.wc(this.Jc,y),r:f.wc(this.md,z),f:x.uc,o:0===q&&g.isBase?1:Math.round(x.$c),m:x.marks,s:a.utils.isDefined(g.transferSize)?g.transferSize:-1})}}};var g=d.Sf();this.mf(g,e);e=this.jh(g,e);this.bf(f||a.monitor.perfMonitor.navTiming&&a.monitor.perfMonitor.navTiming.navigationStart,e);this.clearResourceTimings()}d.Ta=function(){var c=a.conf.userConf&&a.conf.userConf.resTiming&&a.conf.userConf.resTiming.sampler;d.ih=c&&"FirstN"==
c?new b.he:c&&"TopN"==c?new b.Tb:new b.Pe};d.prototype.Gc=function(a,d){a[d]=a[d]?a[d]+1:1};d.prototype.Hh=function(d){return a.utils.Gh(d,"number"===typeof a.conf.userConf.maxResUrlSegmentLength?a.conf.userConf.maxResUrlSegmentLength:a.conf.be,"number"===typeof a.conf.userConf.maxResUrlSegmentNumber?a.conf.userConf.maxResUrlSegmentNumber:a.conf.ce,a.conf.Ie,a.conf.He)};d.prototype.mf=function(a,d){a&&this.Hc(a);if(d&&0<d.length)for(var c=0;c<d.length;c++)this.Hc(d[c])};d.prototype.Hc=function(d){var c=
a.utils.parseURI(a.utils.n.H(d.name)),c=b.V.Ac(c);this.Gc(this.Ic,d.initiatorType);this.Gc(this.ld,c)};d.prototype.jh=function(c,e){if(e&&0<e.length){var b=a.conf.userConf&&a.conf.userConf.resTiming&&a.conf.userConf.resTiming.maxNum||a.conf.De;c&&b--;e=d.ih.ya(e,b);c&&e.unshift(c)}return e};d.prototype.build=function(){return 0==this.hb.length?null:{v:this.version,ic:this.Ic,it:this.Jc,rc:this.ld,rt:this.md,f:b.Pb.Vf(),t:this.Bh,r:this.hb}};d.Sf=function(){var d=a.monitor.perfMonitor.navTiming,c=
null;if(d){var c={},e;for(e in d)f(d,e)&&(c[e]=d[e]);c.initiatorType="other";c.name=document.URL;c.navigationStart&&!c.startTime&&(c.startTime=c.navigationStart);c.isBase=!0}return c};d.prototype.clearResourceTimings=function(){var d=a.monitor.PerformanceMonitor.perf;a.conf.userConf&&a.conf.userConf.resTiming&&a.conf.userConf.resTiming.clearResTimingOnBeaconSend&&d&&a.utils.isFunction(d.clearResourceTimings)&&d.clearResourceTimings()};return d}();b.ResourceTimingInfoBuilder=e;var c=function(){function a(){this.Mg=
1}a.prototype.wc=function(a,d){a[d]||(a[d]=this.Mg++);return a[d]};return a}();e.Ta()})(a.events||(a.events={}))})(g||(g={}));(function(a){a.events||(a.events={})})(g||(g={}));(function(a){(function(b){var f=function(){function e(){}e.prototype.make=function(c,d){void 0===d&&(d={});var e={eventGUID:c.guid(),eventType:c.type(),eventUrl:a.utils.n.H(c.url()||document.URL),timestamp:a.utils.now()};c.type()!==a.EventType.PageView&&a.utils.mergeJSON(e,{parentGUID:c.parentGUID()||a.correlation.getPageGUID(),
parentUrl:a.utils.n.H(c.parentUrl()||document.URL),parentType:c.parentType()||(a.utils.compareWindows(top,window)?a.EventType.PageView:a.EventType.IFRAME)});var f=a.EventType[c.type()],f=b.W.dg(f,a.conf.userConf,d,a.conf.U),g;for(g in f)e[g]=f[g];return e};return e}();b.fa=f})(a.events||(a.events={}))})(g||(g={}));(function(a){(function(b){var f=a.utils.isNumber,e=a.utils.isString,c=a.utils.isObject,d=a.utils.kc,h=a.utils.Ua,g=a.utils.isBoolean,m=function(){function b(){}b.Za=function(d,e){var b=
!1;if(c(d)){var h=a.utils.O(d);if(!h||h.length<=e)b=!0}return b};b.wh=function(a,d,c){if(e(d))if(d.length>c)b.ta(a,c,d.length);else return d;else b.Wa(a,"string")};b.ua=function(a,d){return function(e,h,f){if(c(h)){var g,q;for(q in h)a(h[q])?(g=g||{},g[q]=h[q]):b.Wa(e,d,q);if(g){if(b.Za(g,f))return g;b.ta(e,f)}}else b.Wa(e,"object")}};b.Wa=function(a,c,e){d(a+" dropped because it was not a "+c+(e?", field name "+e:""))};b.ta=function(a,c,e){d("User event info field "+a+" dropped because it is too long"+
(e?" ("+e+" exceeds "+c+")":""))};b.dg=function(d,e,h,f){if(d=e&&e.userEventInfo&&e.userEventInfo[d])if(h=a.utils.isFunction(d)?d.call(null,h):d,c(h))return b.Mh(h,f)};b.Mh=function(a,d){var c={},e;for(e in b.sc)if(e in a){var h=b.sc[e](e,a[e],d);h&&(c[e]=h)}return c};b.Vg=b.ua(e,"string");b.Ug=b.ua(h,"integer");b.Zc=b.ua(f,"number");b.Tg=b.ua(g,"boolean");b.sc={userPageName:b.wh,userData:b.Vg,userDataLong:b.Ug,userDataDouble:b.Zc,userDataBoolean:b.Tg,userDataDate:b.Zc};return b}();b.W=m})(a.events||
(a.events={}))})(g||(g={}));var u=this.$e||function(a,b){function f(){this.constructor=a}for(var e in b)b.hasOwnProperty(e)&&(a[e]=b[e]);f.prototype=b.prototype;a.prototype=new f};(function(a){(function(b){var f=a.utils.isDefined,e=function(c){function d(){c.apply(this,arguments)}u(d,c);d.setPageName=function(a){d.Kh=a};d.addUserData=function(a,c){d.ca=d.ca||{};d.ca[a]=c};d.prototype.make=function(e){e=c.prototype.make.call(this,e||new b.PageView);var g=this.Yf(),m=this.Tf();a.conf.viz&&(g&&a.utils.Ma(document.getElementById(a.conf.viz),
g,"navtime"),a.utils.Ma(document.getElementById(a.conf.viz),m,"cookie"));m.PLC=1;g&&(g.PLC=1);0<a.monitor.ErrorMonitor.errorsSent&&(m.EPM=1,g&&(g.EPM=1));a.utils.mergeJSON(e,{eventGUID:a.correlation.getPageGUID(),eventType:a.utils.compareWindows(top,window)?a.EventType.PageView:a.EventType.IFRAME,cookieMetrics:m});var k=-1;g&&g.timestamp?k=g.timestamp:m&&m.timestamp&&(k=m.timestamp);0<k&&a.utils.mergeJSON(e,{timestamp:k});g&&(e.metrics=g);document.referrer&&null!==document.referrer&&0<document.referrer.length&&
(e.pageReferrer=a.utils.n.H(document.referrer));g=d.Zf();0<g.length&&(e.pageTitle=g);g=a.correlation.Cc();null!==g&&(e.serverMetadata=g);g=a.monitor.perfMonitor.resTiming?(new b.ResourceTimingInfoBuilder(a.monitor.perfMonitor.resTiming)).build():null;null!==g&&(e.resourceTimingInfo=g);!f(e.userData)&&f(d.ca)&&(b.W.Za(d.ca,a.conf.U)?e.userData=d.ca:b.W.ta("userData",a.conf.U));a.utils.isDefined(e.userPageName)||(e.userPageName=d.Kh);d.userPageName=e.userPageName;return e};d.prototype.Yf=function(){if(!a.monitor.perfMonitor.navTiming)return null;
var c={},e=d.yc(a.monitor.perfMonitor.navTiming,c,"NT"),f=b.metricSpec[a.EventType.PageView],g;for(g in f){var s=f[g];e.add(s.name,s.start,s.end)}c.timestamp=a.monitor.perfMonitor.navTiming.navigationStart;return c};d.prototype.Tf=function(){var c={};a.commands.marks&&(d.yc(a.commands.marks,c,"CK").add("PLT","starttime","onload").add("FBT","starttime","firstbyte").add("FET","firstbyte","onload").add("DRT","firstbyte","onready").add("PRT","onready","onload").add("DOM","starttime","onready"),c.timestamp=
a.commands.marks.starttime?a.commands.marks.starttime:a.commands.marks.firstbyte);return c};d.Zf=function(){var d=a.conf.userConf,d=d&&d.page,c;c=d&&"captureTitle"in d?d.captureTitle:!0;var e,b;d&&(e="title"in d,b=d.title);e=c?e?a.utils.isFunction(b)?b():b:document.title:"";if(a.utils.isString(e))return e;a.utils.kc("Ignoring wrong type of page title: "+typeof e);return""};d.af=function(d,c,e,b,f,g){c=b[c];e=b[e];c&&e?f[d]=e-c:a.log("M87",g,d,c,e)};d.yc=function(a,c,e){var b={add:function(f,g,l){d.af(f,
g,l,a,c,e);return b}};return b};return d}(b.fa);b.D=e})(a.events||(a.events={}))})(g||(g={}));(function(a){(function(b){(function(b){function e(b,h){var f,k=h[b],n=typeof k;t.push(b);var C=r[t.join(".")];if(a.utils.isFunction(C))f=C(k);else switch(n){case "string":f="number"==typeof C?s(k,d,C):d(k);break;case "number":f=m(k);break;case "object":if(k)if(a.utils.isArray(k))f=g(k,!1,!1);else{f=[];for(var v in k)l(k,v)&&(n=e(v,k))&&(c(b)&&"timestamp"==v||f.push({sa:v,v:n}));if(c(b)){for(k=0;k<f.length;k++)f[k]=
f[k].sa+d(":")+f[k].v;f=d("{")+f.join(d(","))+d("}")}else{for(k=0;k<f.length;k++)v=f[k],n=v.sa,a.conf.Hd||((C=a.conf.Tc[v.sa])?n=C:a.error("M88",v.sa)),f[k]=n+"="+v.v;f=f.join("&")}}else f=null}t.pop();return f}function c(a){return"navOrXhrMetrics"==a||"cookieMetrics"==a}function d(a){return"undefined"===typeof a||null===a||0===a.length?null:encodeURIComponent(a)}function h(a){return encodeURIComponent(encodeURIComponent(a))}function g(a,c,b){void 0===c&&(c=!1);void 0===b&&(b=!0);if(0===a.length)return null;
var f=[];if(c)f=a;else for(c=0;c<a.length;c++)f.push(e(c,a));return d("[")+f.join(d(","))+d(b?">":"]")}function m(a){a=Math.round(a);a<b.Nb&&(a=b.Nb);a>b.Kb&&(a=b.Kb);return d(a)}function k(a,c){if(a>c||0>a)a=b.Me;return d(a)}function s(d,c,e,b){void 0===b&&(b=!0);if("undefined"===typeof d||null===d||0===d.length)return null;var f=3<=e?"...":"";a.assert(e>=f.length);for(var h=!1,g=null;;){try{g=c(d);if(null===g)return null;if(g.length<=e)break}catch(q){}var k;h?k=d.length-1:(h=!0,k=e-=f.length);var m=
b?0:Math.max(d.length-k,0);d=d.substr(m,k)}h&&(g=b?g+f:f+g);return g}function n(d,c,e){if(0==e)return b.Da;if(c<d)return 0;c=b.Da+(c-d)/e;a.assert(c>=b.Da);a.log("M89",d,c);return c}var l=a.utils.hasOwnPropertyDefined;b.Me=-1;b.J=180;b.Fe=50;b.Ge=50;b.Ae=40;b.Da=50;b.pe=50;b.Mb=128;b.ve=30;b.we=30;b.ue=30;b.Be=8;b.Nb=-99999;b.Kb=999999;b.qe=2E3;b.Ee=2;b.re=99999999;var r={".pageUrl":b.J,".parentPageUrl":b.J,".pageReferrer":b.J,".pageTitle":b.Fe,".userPageName":b.Ge,".geoCountry":b.ve,".geoRegion":b.we,
".geoCity":b.ue,".localIP":b.Be,".otherClientRequestGUIDs":function(a){a=a||[];var d=a.slice(0,b.Ee);return g(d,!1,d.length<a.length)},".btTime":function(d){d=d||[];for(var c=d.slice(0,a.conf.se),e=[],h=0;h<c.length;h++){var r=c[h];e.push(g([k(Number(r[0]),b.re),m(r[1]),m(r[2])],!0,!1))}return g(e,!0,c.length<d.length)},".ajaxError":function(a){return g([h(a[0]),s(a[1],h,b.pe)],!0,!1)},".userData":function(a){a=a||[];for(var d=!1,c=0,e=[],k=0;k<a.length;k++){var m=a[k];e[k]=g([h(m[0]),h(m[1])],!0,
!1);c+=e[k].length;if(c>b.Mb){d=!0;break}}for(;;){a=g(e,!0,d);if(null===a||a.length<=b.Mb)return a;e.pop();d=!0}}},t=[];b.Ef=function(d,c){void 0===c&&(c=!0);t=[];var k=[];d.errors&&(k=d.errors,d.errors=null);var r=e("",{"":d});if(k&&0<k.length){for(var l=n(c?870:354,b.qe-r.length,k.length),C=[],v=0;v<k.length;v++){var u=k[v],A=a.utils.n.qc(a.utils.n.H(u[0]));C.push(g([s(A,h,b.Ae,!1),a.utils.Ua(u[1])?m(u[1]):-1,s(u[2],h,l)],!0,!1))}k=g(C,!0,!1);r+="&errors="+k}return r};b.ni=e;b.Hi=d;b.element=h;
b.hi=g;b.ji=m;b.zi=k;b.truncate=s;b.Ei=n})(b.Hb||(b.Hb={}))})(a.beacons||(a.beacons={}))})(g||(g={}));(function(a){(function(b){var f=a.utils.hasOwnPropertyDefined,e=function(){function c(){}c.prototype.Xa=function(d,e,f){for(var g=[],k=[],s=null,n=[],l=0;l<d.length;l++){var r=d[l];if(r.eventType===a.EventType.Error){var t=r;k.push([r.eventUrl+"",a.utils.Ua(t.line)?t.line:void 0,t.message+""])}else{if(r.eventType===a.EventType.PageView||r.eventType===a.EventType.IFRAME)s=r;n.push(r)}}d=n;if(0<k.length)for(s&&
(s.errors=k.splice(0,a.conf.ye));0<k.length;)r=k.splice(0,a.conf.xe),s=c.Yg.make(),s.errors=r,s.isErrorEvent=!0,s.cookieMetrics=null,s.metrics=null,s.resourceTimingInfo=null,d.push(s);for(k=0;k<d.length;k++)r=d[k],a.log("M90"),r.resourceTimingInfo=null,c.Pf(r,e,f),s=c.transform(r),g.push(b.Hb.Ef(s,r.isErrorEvent));return g};c.Pf=function(d,c,e){d.ver=this.ke;d.rootGUID=e.Bc();d.geo=c;d.dataType="R";d.eom=1;d.eumAppKey=a.conf.appKey;d.PLC=1};c.transform=function(a){var e={};c.Md("",{"":a},e);return e};
c.Md=function(d,e,b){e=e[d];var g=c.Qc[d];if("metrics"===d||"cookieMetrics"===d)b[g]=e;else if("btTime"===d&&a.utils.isArray(e)&&0<e.length){d=[];for(var k=0;k<e.length;k++)d.push([e[k].id,e[k].duration,e[k].ert]);b[g]=d}else if("userData"===d&&a.utils.isObject(e))b[g]=a.utils.Jg(e);else if(a.utils.isObject(e))for(k in e)f(e,k)&&c.Md(k,e,b);else c.Qc[d]&&("eventType"===d&&e>a.EventType.Ajax&&(e=a.utils.compareWindows(top,window)?a.EventType.PageView:a.EventType.IFRAME),b[g]=e)};c.Yg=new a.events.D;
c.ke=3;c.Qc={eumAppKey:"eumAppKey",userPageName:"userPageName",rootGUID:"baseGUID",parentGUID:"parentGUID",parentUrl:"parentPageUrl",parentType:"parentPageType",parentLifecyclePhase:"parentLifecyclePhase",eventType:"pageType",eventUrl:"pageUrl",pageReferrer:"pageReferrer",pageTitle:"pageTitle",metrics:"navOrXhrMetrics",xhrMetrics:"navOrXhrMetrics",resourceTimingInfo:"resourceTimingInfo",cookieMetrics:"cookieMetrics",userData:"userData",errors:"errors",ajaxError:"ajaxError",dataType:"dataType",country:"geoCountry",
region:"geoRegion",city:"geoCity",localIP:"localIP",ver:"ver",eom:"eom",eventGUID:"clientRequestGUID",otherClientRequestGUIDs:"otherClientRequestGUIDs",btTime:"btTime",serverSnapshotType:"serverSnapshotType",hasEntryPointErrors:"hasEntryPointErrors"};return c}();b.ne=e})(a.beacons||(a.beacons={}))})(g||(g={}));(function(a){(function(a){var f=function(){function a(){}a.prototype.send=function(){};return a}();a.fe=f})(a.beacons||(a.beacons={}))})(g||(g={}));(function(a){(function(a){var f=function(){function a(){}
a.prototype.Xa=function(){return null};return a}();a.ee=f})(a.beacons||(a.beacons={}))})(g||(g={}));(function(a){var b=function(){function b(){}b.jc=function(e,c){if(!e)return null;var d=e.ADRUM.lifecycle;if(!d||!d.getPhaseCallbackTime)return null;var b=c.getPhaseCallbackTime("AT_ONLOAD"),d=d.getPhaseCallbackTime("AT_ONLOAD"),f=null==d;return null==b?(a.error("M91"),null):a.lifecycle.getPhaseID(f||b<=d?"AFTER_FIRST_BYTE":"AFTER_ONLOAD")};return b}();a.Oe=b;a.cPLPI=b.jc})(g||(g={}));(function(a){(function(b){var f=
function(){function e(c){this.ready=!1;this.geoResolverUrl=c;a.utils.isString(c)&&0<a.utils.trim(c).length&&(this.geoResolverUrl=c+"/resolve.js")}e.prototype.init=function(c){this.channel=c;if(this.Ka()&&(a.geo=this.pb(),this.ff()||this.va()&&!this.vc())){this.channel.jb(a.geo.result);return}this.vc()?(this.va()&&(this.geoResolverUrl+="?ip="+encodeURIComponent(a.conf.userConf.geo.localIP)),this.Jh()):(this.ready=!0,this.channel.onResolverReady())};e.prototype.Ka=function(){return a.utils.isDefined(a.conf.userConf)&&
a.utils.isDefined(a.conf.userConf.geo)};e.prototype.va=function(){return this.Ka()&&a.utils.isDefined(a.conf.userConf.geo.localIP)&&!a.utils.isDefined(a.conf.userConf.geo.city)&&!a.utils.isDefined(a.conf.userConf.geo.region)&&!a.utils.isDefined(a.conf.userConf.geo.country)};e.prototype.pb=function(){return{failed:!1,result:{country:a.conf.userConf.geo.country,region:a.conf.userConf.geo.region,city:a.conf.userConf.geo.city,localIP:this.Gf(a.conf.userConf.geo.localIP)}}};e.prototype.ff=function(){return this.Ka()&&
a.utils.isDefined(a.conf.userConf.geo.localIP)&&a.utils.isDefined(a.conf.userConf.geo.city)&&a.utils.isDefined(a.conf.userConf.geo.region)&&a.utils.isDefined(a.conf.userConf.geo.country)};e.prototype.vc=function(){return a.utils.isString(this.geoResolverUrl)&&0<a.utils.trim(this.geoResolverUrl).length};e.prototype.Gf=function(a){if(null==a||0==a.length)return null;a=a.split(".");if(4!=a.length)return null;for(var d=[],e=0;e<a.length;e++){var b=parseInt(a[e]);if(isNaN(b)||0>b||255<b)return null;d.push(("0"+
b.toString(16)).slice(-2))}return d.join("")};e.prototype.Jh=function(){a.geo={failed:!1,result:null};a.utils.loadScriptAsync(this.geoResolverUrl);var c=this;a.utils.tryPeriodically(e.Ha,function(){return c.isReady()},function(){c.onReady()},function(){c.$a()})};e.prototype.isReady=function(){this.ready||(this.ready=a.geo&&(a.geo.failed||null!==a.geo.result))||a.log("M92");return this.ready};e.prototype.onReady=function(){a.geo.failed?(a.log("M93"),this.va()&&(a.geo=this.pb())):(a.assert("object"===
typeof a.geo.result),a.log("M94",a.geo.result));a.geo&&a.geo.result&&this.channel.jb(a.geo.result);this.channel.onResolverReady()};e.prototype.$a=function(){a.log("M95");this.va()&&(a.geo=this.pb());a.geo&&a.geo.result&&this.channel.jb(a.geo.result);this.ready=!0;this.channel.onResolverReady()};e.Ha=function(a){return 10<a?-1:[1,50,100,500][a-1]||1E3};return e}();b.ie=f})(a.channel||(a.channel={}))})(g||(g={}));(function(a){(function(b){var f=function(){function e(){this.ready=!1;this.channel=null}
e.prototype.init=function(c){this.channel=c;e.p=e.p||e.Rf();this.ready=!e.p.qa;var d=this;if(e.p.qa)a.log("M96"),e.p.qa.ADRUM.command("listenForOkToSendChildFrameBeacons",function(){a.log("M97");d.ready=!0;d.onReady()});else d.onReady()};e.prototype.isReady=function(){this.isReady||a.log("M98");return this.ready};e.prototype.onReady=function(){this.channel.nh(e.p);this.channel.onResolverReady()};e.Rf=function(){for(var c=window,d,b=e.Nc(c),f=window;a.utils.Eg(f.parent)&&!a.utils.compareWindows(f,
f.parent);){f=f.parent;b=b||e.Nc(f);try{f.ADRUM&&(d=d||f,c=f)}catch(g){}}return new a.Vd(d,c,b)};e.Nc=function(a){try{return 0==a.document.URL.indexOf("https:")}catch(d){}};e.p=null;return e}();b.Wd=f})(a.channel||(a.channel={}))})(g||(g={}));(function(a){(function(b){var f=function(){function c(d,c,e){this.events=[];this.K={};this.oa=NaN;this.G=[];this.Pa=!1;this.bufferMode=a.conf.userConf&&a.conf.userConf.channel&&"undefined"!==typeof a.conf.userConf.channel.bufferMode?a.conf.userConf.channel.bufferMode:
!0;this.za=-1;this.Ch=d;this.gf=c;this.G.push(new b.ie(e));this.G.push(new b.Wd);this.G.push(new b.I)}c.create=function(){var d,e;c.rg()&&!a.conf.sendImageBeacon?(d=new a.beacons.Yd,e=new a.beacons.Xd):c.wg()?(d=new a.beacons.fe,e=new a.beacons.ee):(d=new a.beacons.oe,e=new a.beacons.ne);d=new c(d,e,a.conf.geoResolverUrl);d.init();return d};c.prototype.init=function(){for(var a=0;a<this.G.length;a++)this.G[a].init(this)};c.prototype.Ph=function(d){return(d.parentType===a.EventType.VPageView||d.parentType===
a.EventType.NG_VIRTUAL_PAGE)&&null!==this.K[d.parentGUID]};c.prototype.eh=function(d){var c=d.parentGUID;if(!a.utils.isDefined(this.K[c])){this.K[c]=[];var e=this,b=d.eventGUID;setTimeout(function(){e.La(b)},1E4)}this.K[c].push(d)};c.prototype.report=function(d){d.sequenceId=a.ud.gc.Uf();d.timestamp=d.timestamp||a.utils.now();this.Ph(d)?this.eh(d):this.events.push(d);1==this.events.length&&(this.oa=a.utils.now());var e=d.parentGUID;e&&e!==a.correlation.getPageGUID()||this.La(d.eventGUID);c.vg(d)&&
(this.Pa=!0);this.nb()};c.prototype.La=function(a){var c=this.K[a];this.K[a]=null;if(c&&0!=c.length)for(this.events=this.events.concat(c),a=0;a<c.length;a++)this.La(c[a].eventGUID)};c.prototype.yg=function(d){return d.eventType===a.EventType.PageView||d.eventType===a.EventType.IFRAME};c.prototype.hf=function(){for(var d=0;d<this.events.length;d++){var c=this.events[d];if(this.yg(c)){var e=this.p.qa;e&&(c.parentLifecyclePhase=a.Oe.jc(e,a.lifecycle),c.parentGUID=e.ADRUM.correlation.getPageGUID(),c.parentUrl=
a.utils.n.H(e.document.URL),a.utils.isDefined(e.ADRUM.events.D.userPageName)&&(c.parentPageName=e.ADRUM.events.D.userPageName),c.parentType=a.utils.compareWindows(top,e)?a.EventType.PageView:a.EventType.IFRAME)}}};c.prototype.lh=function(){if(0==this.events.length)a.log("M99");else{this.hf();var d=this.qb(this.events,this.p),c=this.gf.Xa(this.events,this.Qf,this.p);this.Ch.send(c,d);this.events=[];this.oa=Number.POSITIVE_INFINITY}};c.prototype.onResolverReady=function(){this.nb()};c.prototype.jb=
function(a){this.Qf=a};c.prototype.nh=function(a){this.p=a};c.prototype.addResolver=function(a){a.init(this);this.G.push(a)};c.prototype.hh=function(){for(var a=0;a<this.G.length;a++)if(!this.G[a].isReady())return!1;return!0};c.prototype.Pc=function(){return this.oa+a.conf.Jb>a.utils.now()};c.prototype.zg=function(){return this.events.length<a.conf.te};c.prototype.qb=function(d,c){if(c.qb||a.conf.userConf.useHTTPSAlways)return!0;for(var e=0;e<d.length;e++){var b=d[e];if(b.eventUrl&&0==b.eventUrl.indexOf("https:"))return!0}return!1};
c.prototype.getEventsWithParentGUID=function(a){return this.K[a]||[]};c.prototype.nb=function(){if(this.hh())if(this.Oh()){if(this.Pc()&&0<this.events.length&&0>this.za){var d=this;this.za=setTimeout(function(){d.nb()},a.conf.Jb+this.oa-a.utils.now())}}else clearTimeout(this.za),this.za=-1,this.Pa=!1,this.lh()};c.vg=function(d){return d.eventType===a.EventType.PageView||d.eventType===a.EventType.IFRAME||d.eventType===a.EventType.VPageView};c.prototype.Oh=function(){return this.bufferMode&&!this.Pa&&
this.zg()&&this.Pc()};c.rg=function(){var a="undefined"!==typeof JSON&&!(!JSON||!JSON.stringify);return window.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest&&a};c.wg=function(){return a.conf.userConf&&a.conf.userConf.beacon&&a.conf.userConf.beacon.neverSendImageBeacon};return c}();b.Channel=f;var e=f.create();b.report=function(a){e.report(a)};b.addResolver=function(a){e.addResolver(a)};b.getEventsWithParentGUID=function(a){return e.getEventsWithParentGUID(a)}})(a.channel||(a.channel={}))})(g||
(g={}));(function(a){var b=function(){function b(){}b.dd=function(){return window.attachEvent?a.utils.isFunction(window.addEventListener)?this.rb:this.Dd:this.Gd};b.cd=function(e){var c=null;switch(b.dd()){case b.Gd:c=e.parentPhase();break;case b.rb:c=a.lifecycle.findPhaseAtNominalTime(e.getSendTime());break;case b.Dd:c=null}return a.lifecycle.getPhaseID(c)};b.Gd="uCT";b.rb="uNET";b.Dd="tIA";return b}();a.ka=b})(g||(g={}));(function(a){(function(b){var f=a.utils.hasOwnPropertyDefined,e=function(c){function d(){c.apply(this,
arguments)}u(d,c);d.prototype.make=function(e){var f=c.prototype.make.call(this,e,d.getContext(e)),g=e.url(),k=e.getSendTime(),s=e.getFirstByteTime(),n=e.getRespAvailTime(),l=e.getRespProcTime();a.assert(null!==g&&null!==k&&null!==s&&null!==n&&null!==l,"missing some pieces of XHR data: url="+g+", send="+k+", fbt="+s+", rat="+n+", eut="+l+", parentPhase="+e.parentPhase());if(null===g||null===k||null===s||null===n||null===l)return null;g=e.error();k={PLC:1,FBT:s-k,DDT:n-s,DPT:l-n,PLT:l-k,ARE:g?1:0};
s=e.url();if(!d.Gg(k,s))return null;a.conf.viz&&a.utils.Ma(document.getElementById(a.conf.viz),k,"xhr");a.utils.mergeJSON(f,{eventUrl:a.utils.n.H(s),parentType:e.parentType()||a.EventType.PageView,parentLifecyclePhase:e.parentPhaseId(),metrics:k,method:e.method(),timestamp:e.timestamp(),ajaxError:g&&[g.status,g.msg||""],xhrStatus:e.xhrStatus()});(e=e.parameter())&&b.W.Za(e,a.conf.U)?f.parameter=e:e&&b.W.ta("parameter",a.conf.U);a.utils.oh(f,b.D.userPageName);return f};d.getContext=function(a){return{url:a.url()||
"",method:a.method()||""}};d.Gg=function(e,d){for(var c in e)if(f(e,c)){var b=e[c];if(0>b)return a.error("XHR "+c+" ["+b+"] "+d),!1}return!0};return d}(b.fa);b.Vb=e})(a.events||(a.events={}))})(g||(g={}));(function(a){(function(b){var f=function(e){function c(){e.apply(this,arguments)}u(c,e);c.prototype.make=function(d){var c=e.prototype.make.call(this,d);c&&(d=d.allResponseHeaders()||"",(d=a.correlation.cg(d))&&null!==d&&null!==d.clientRequestGUID&&(c.eventGUID=d.clientRequestGUID),null!==d&&(c.serverMetadata=
d));return c};return c}(b.Vb);b.Qd=f})(a.events||(a.events={}))})(g||(g={}));(function(a){(function(b){var f=function(e){function c(){e.apply(this,arguments)}u(c,e);c.prototype.make=function(d){var c=e.prototype.make.call(this,d);a.utils.mergeJSON(c,{message:d.msg()||"",timestamp:d.timestamp(),line:d.line(),stack:d.stack(),parentPageName:b.D.userPageName});a.utils.isString(c.userPageName)||(c.userPageName=c.parentPageName);return c};return c}(b.fa);b.Ne=f})(a.events||(a.events={}))})(g||(g={}));(function(a){(function(a){(function(f){f.build=
function(e){var c={},d=a.metricSpec[e.type()],f;for(f in d){var g=d[f];if(null!==g.name&&e.perf.getEntryByName(g.start)&&e.perf.getEntryByName(g.end)){e.perf.measure(g.name,g.start,g.end);var m=e.perf.getEntryByName(g.name);c[g.name]=m&&0<=m.duration&&m.duration||null}}for(f in c)c[f]=Math.round(c[f]);return c}})(a.Sb||(a.Sb={}))})(a.events||(a.events={}))})(g||(g={}));(function(a){(function(a){var f=function(e){function c(){e.apply(this,arguments)}u(c,e);c.prototype.make=function(d){var c=e.prototype.make.call(this,
d),f=a.Sb.build(d);f.PLC=1;c.metrics=f;c.timestamp=d.timestamp();d=(new a.ResourceTimingInfoBuilder(d.resTiming())).build();null!==d&&(c.resourceTimingInfo=d);return c};return c}(a.fa);a.Ub=f})(a.events||(a.events={}))})(g||(g={}));(function(a){(function(a){var f=function(a){function c(){a.apply(this,arguments)}u(c,a);c.prototype.make=function(c){var b=a.prototype.make.call(this,c);b&&(b.metrics.VDC=c.digestCount()||0);return b};return c}(a.Ub);a.Le=f})(a.events||(a.events={}))})(g||(g={}));(function(a){var b=
a.events||(a.events={});b.jd={};a=[{P:b.PageView,M:new b.D},{P:b.Ajax,M:new b.Vb},{P:b.AdrumAjax,M:new b.Qd},{P:b.Error,M:new b.Ne},{P:b.VPageView,M:new b.Ub},{P:a.ng.NgVPageView,M:new b.Le}];for(var f=0;f<a.length;f++){var e=a[f];e.P.prototype._regId=f;b.jd[f]=e.M}})(g||(g={}));(function(a){(function(b){b.reportEvent=function(b){var e=a.events.jd[b._regId];e?(e=e.make(b),a.utils.isDefined(e)&&(a.log("M101",a.EventType[b.type()]),a.channel.report(e))):a.log("M100"+a.EventType[a.eventType])}})(a.reporter||
(a.reporter={}))})(g||(g={}));(function(a){(function(b){var f=function(){function e(){this.ready=!1}e.prototype.onReady=function(){this.ready=!0;this.channel.onResolverReady()};e.prototype.isReady=function(){this.ready||a.log("M102");return this.ready};e.prototype.init=function(a){this.channel=a};return e}();b.Ze=f})(a.commands||(a.commands={}))})(g||(g={}));(function(a){(function(b){var f=new b.Ze;a.channel.addResolver(f);b.marks={};b.mark=function(e,c){a.log("M103",e,c);b.marks[e]=c};b.reportOnload=
function(e){setTimeout(function(){a.log("M104");a.reporter.reportEvent(e);f.onReady()},a.conf.Xe)};b.reportEvent=function(){a.reporter.reportEvent.apply(a.reporter,arguments)};b.addResolver=function(e){a.channel.addResolver(e)};b.reportXhr=function(e){a.log("M105");a.ka.dd()==a.ka.rb?(a.log("M106"),setTimeout(function(){e.parentPhaseId(a.ka.cd(e));a.reporter.reportEvent(e)},0)):(e.parentPhaseId(a.ka.cd(e)),a.reporter.reportEvent(e))};b.listenForOkToSendChildFrameBeacons=function(e){a.log("M107");
try{e()}catch(c){a.exception(c,"M108")}};b.reportPageError=function(e){var c=e.url();a.log("M109",e.msg(),c,e.line(),e.stack());c&&0!==c.length||e.url("CROSSORIGIN");a.reporter.reportEvent(e)};b.setPageName=function(e){a.events.D.setPageName(e)};b.addUserData=function(e,c){a.events.D.addUserData(e,c)};b.call=function(a){a()}})(a.commands||(a.commands={}))})(g||(g={}));(function(a){(function(a){a.oc=function(f){return encodeURIComponent(a.n.Sg(f))}})(a.utils||(a.utils={}))})(g||(g={}));(function(a){(function(b){var f=
function(){function e(){}e.prototype.setUp=function(){this.Kg();a.utils.addEventListener(window,"pagehide",e.xb);a.utils.addEventListener(window,"beforeunload",e.xb);a.utils.addEventListener(window,"unload",e.xb)};e.prototype.Kg=function(){(this.startTime=e.Nf()||e.Mf())&&a.commands.mark("starttime",this.startTime)};e.Nf=function(){var c;try{if(a.utils.isDefined(window.external)&&a.utils.isNumber(window.external.pageT))c=(new Date).getTime()-window.external.pageT;else if(a.utils.isDefined(window.Dc)&&
a.utils.isFunction(window.Dc.pageT)){var e=window.Dc.pageT();a.utils.isNumber(e)&&(c=(new Date).getTime()-e)}else a.utils.isDefined(window.chrome)&&a.utils.isFunction(window.chrome.csi)&&(e=window.chrome.csi(),a.utils.isDefined(e)&&a.utils.isNumber(e.pageT)&&(c=(new Date).getTime()-e.pageT));c&&(c=Math.round(c),a.log("M110",c))}catch(b){a.exception(b,"M111")}return c};e.Mf=function(){var e=a.correlation.startTimeCookie;if(e){a.log("M112",e.startTime,e.startPage);var d=a.utils.oc(document.referrer);
if(d===e.startPage)if(isNaN(e.startTime))a.log("M113",e.startTime);else return e.startTime;else a.log("M114",d,e.startPage)}else a.log("M115")};e.Af=function(e,d){var b=document.domain,f="https:"===document.location.protocol,g="ADRUM=s="+Number(new Date)+"&r="+a.utils.oc(document.location.href),k=g+";path=/";f&&(k+=";secure");a.log("M116",g);if(!a.conf.useStrictDomainCookies){for(var f=e(),b=b.split("."),s="",n=b.length-1;0<=n;n--){s="."+b[n]+s;a.log("M117",s);d(k+";domain="+s);var l=e();if(l!=f&&
0<=l.indexOf(g)){a.log("M118");a.log("M119");return}}a.log("M120")}a.log("M121");d(k);a.log("M122")};e.xb=function(){var a=!1;return function(){a||(a=!0,e.Af(function(){return document.cookie},function(a){document.cookie=a}))}}();return e}();b.ai=f;b.vh=new f})(a.monitor||(a.monitor={}))})(g||(g={}));(function(a){a.log("M123");a.monitor.vh.setUp();a.q.processQ();a.initEXTDone=!0;a.log("M124")})(g||(g={}))}};})();
